//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.BooksReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BooksReference.IBook", CallbackContract=typeof(WPF.BooksReference.IBookCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetAll", ReplyAction="http://tempuri.org/IBook/GetAllResponse")]
        WPF.BooksReference.Book[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetAll", ReplyAction="http://tempuri.org/IBook/GetAllResponse")]
        System.Threading.Tasks.Task<WPF.BooksReference.Book[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetByAuthor", ReplyAction="http://tempuri.org/IBook/GetByAuthorResponse")]
        WPF.BooksReference.Book[] GetByAuthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetByAuthor", ReplyAction="http://tempuri.org/IBook/GetByAuthorResponse")]
        System.Threading.Tasks.Task<WPF.BooksReference.Book[]> GetByAuthorAsync(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Add", ReplyAction="http://tempuri.org/IBook/AddResponse")]
        void Add(WPF.BooksReference.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Add", ReplyAction="http://tempuri.org/IBook/AddResponse")]
        System.Threading.Tasks.Task AddAsync(WPF.BooksReference.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Modify", ReplyAction="http://tempuri.org/IBook/ModifyResponse")]
        void Modify(int id, WPF.BooksReference.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Modify", ReplyAction="http://tempuri.org/IBook/ModifyResponse")]
        System.Threading.Tasks.Task ModifyAsync(int id, WPF.BooksReference.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Delete", ReplyAction="http://tempuri.org/IBook/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/Delete", ReplyAction="http://tempuri.org/IBook/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBook/Contains")]
        void Contains(WPF.BooksReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBook/Contains")]
        System.Threading.Tasks.Task ContainsAsync(WPF.BooksReference.Book book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBook/ContainsResult")]
        void ContainsResult(bool result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookChannel : WPF.BooksReference.IBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookClient : System.ServiceModel.DuplexClientBase<WPF.BooksReference.IBook>, WPF.BooksReference.IBook {
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public WPF.BooksReference.Book[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WPF.BooksReference.Book[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public WPF.BooksReference.Book[] GetByAuthor(string author) {
            return base.Channel.GetByAuthor(author);
        }
        
        public System.Threading.Tasks.Task<WPF.BooksReference.Book[]> GetByAuthorAsync(string author) {
            return base.Channel.GetByAuthorAsync(author);
        }
        
        public void Add(WPF.BooksReference.Book newBook) {
            base.Channel.Add(newBook);
        }
        
        public System.Threading.Tasks.Task AddAsync(WPF.BooksReference.Book newBook) {
            return base.Channel.AddAsync(newBook);
        }
        
        public void Modify(int id, WPF.BooksReference.Book newBook) {
            base.Channel.Modify(id, newBook);
        }
        
        public System.Threading.Tasks.Task ModifyAsync(int id, WPF.BooksReference.Book newBook) {
            return base.Channel.ModifyAsync(id, newBook);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Contains(WPF.BooksReference.Book book) {
            base.Channel.Contains(book);
        }
        
        public System.Threading.Tasks.Task ContainsAsync(WPF.BooksReference.Book book) {
            return base.Channel.ContainsAsync(book);
        }
    }
}
